version: '3'

services:
selenium-hub:
 image:selenium/hub
ports:
- "4442-4444"
networks:
    - grid
node-chrome:
 image:selenium/node-chrome
environment:
- SE_EVENT_BUS_HIST=selenium-hub
- SE_EVENT_BUS_PUBLISH_PORT=4442
- SE_EVENT_BUS_SUBSCRIBE_PORT=4443

node-firefox:
  image:selenium/node-firefox
 environment:
- SE_EVENT_BUS_HIST=selenium-hub
- SE_EVENT_BUS_PUBLISH_PORT=4444
- SE_EVENT_BUS_SUBSCRIBE_PORT=4444

driver: bridge